apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grpc-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
spec:
  tls:
  - hosts:
    - "*.mcbeam.dev"
    secretName: proxy-tls
  rules:
  - host: "proxy.mcbeam.dev"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: micro-proxy
            port:
              number: 8081
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - "*.mcbeam.dev"
    - "*.mcbeam.dev"
    secretName: api-tls
  rules:
  - host: "api.mcbeam.dev"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: micro-api
            port:
              number: 8080
  - host: "*.mcbeam.dev"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: micro-api
            port:
              number: 8080
